[app]
title = HACK DROID BUILDER
package.name = hackdroidbuilder
package.domain = org.hackdroid
source.dir = .
source.include_exts = py,png,jpg,jpeg,kv,atlas,json
version = 1.0.0
requirements = python3,kivy==2.2.0
orientation = portrait
fullscreen = 0
android.permissions = INTERNET,ACCESS_NETWORK_STATE,ACCESS_WIFI_STATE,CHANGE_WIFI_STATE,ACCESS_FINE_LOCATION,ACCESS_COARSE_LOCATION,BLUETOOTH,BLUETOOTH_ADMIN,BLUETOOTH_CONNECT,BLUETOOTH_SCAN,BLUETOOTH_ADVERTISE,NFC,CAMERA,RECORD_AUDIO,VIBRATE,READ_MEDIA_IMAGES,READ_MEDIA_VIDEO,READ_MEDIA_AUDIO,READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE,POST_NOTIFICATIONS,FOREGROUND_SERVICE,WAKE_LOCK,RECEIVE_BOOT_COMPLETED,REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,USE_BIOMETRIC,BODY_SENSORS,ACTIVITY_RECOGNITION,READ_CONTACTS,WRITE_CONTACTS,READ_CALENDAR,WRITE_CALENDAR,READ_CALL_LOG,WRITE_CALL_LOG,READ_PHONE_STATE,CALL_PHONE,SEND_SMS,READ_SMS,RECEIVE_SMS,INSTALL_PACKAGES
android.api = 34
android.minapi = 26
android.ndk = 25b
android.archs = arm64-v8a
android.accept_sdk_license = True
android.private_storage = True
android.allow_backup = False

[buildozer]
log_level = 2
warn_on_root = 1